backend/admins/urls.py
from django.urls import path
from . import views

app_name = 'admins'

urlpatterns = [
    path('', views.home, name='home'),
    path('<str:compiname>', views.compi, name='compi'),
    path('export-csv-all/', views.export_data_to_csv_all, name='export-csv-all'),
    path('export-compi-team-csv/', views.download_compi_team_csv, name='export-compi-team-csv'),
    path('download_csv_ofCompi/<str:compiname>/', views.download_csv_ofCompi, name='download_csv_ofCompi'),
    path('download_csv_ofCompiTeam/<str:compiname>/', views.download_csv_ofCompiTeam, name='download_csv_ofCompiTeam'),
    path('worki/<str:workshopname>', views.workshop, name='workshop'),
    path('download_workshop_csv/<str:workshopname>/', views.download_workshop_csv, name='download_workshop_csv'),
]

backend/apis/urls.py
from django.urls import path
from . import views

app_name = 'apis'

urlpatterns = [
    path('compi_card/', views.compi_card, name='compi_card'),
    path('compi_reg/', views.compi_reg_form, name='compi_reg_form'),
    path('page/', views.page, name='page'),
    path('mail1/', views.mail_bhejo1, name='mail_bhejo1'),
    path('mail2/', views.mail_bhejo2, name='mail_bhejo2'),
    path('mail3/', views.mail_bhejo3, name='mail_bhejo3'),
    # path('profile/', views.ProfileView, name='profile'),
    path('create_team/', views.create_team, name='create_team'),
    path('single_parti/', views.single_parti, name='single_parti'),
    path('check_reg/', views.check_reg, name='check_reg'),
    path('join_team/', views.join_team, name='join_team'),
    path('add_parti/', views.add_parti, name='add_parti'),
    path('leave_team/', views.leave_team, name='leave_team'),
    path('delete_team/', views.delete_team, name='delete_team'),
    path('notify/', views.NotifyView.as_view(), name='notify'),
    path('workshop/', views.workshop_card, name='workshop_card'),
    path('workshop_reg/', views.workshop_reg_form, name='workshop_reg_form'),
    path('robowars/', views.robowar_card, name='robowars_card'),
    path('robowars_reg/', views.robowars_reg_form, name='robowars_reg_form'),
    path('acco_reg/', views.acco_reg, name='acco_reg'),
    path('acco_proof/', views.proof_upload, name='proof_upload'),
    path('sustaintest_reg/', views.sustain_reg_test, name='sustain_reg_test'),    
    path('sustainwebinar_reg/', views.sustain_reg_test, name='sustain_reg_webinar'),
    path('summits/', views.summits, name='summits'),
    path('summitSpeaker/', views.summitSpeaker, name='summitSpeaker'),
    path('summitReg/', views.summitRegForm, name='summitReg'),
    path('ift/', views.ift, name='ift'),
    path('iftReg/', views.iftReg, name='iftReg'),
    path('faces/', views.faces, name='faces'),
    path('appdata/', views.appdata, name='appdata'),
]

backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve
from django.http import HttpResponseRedirect

def custom_404(request, exception):
    return HttpResponseRedirect('https://techfest.org')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('apis.urls')),
    path('administrator/',include('admins.urls'), name="administrator"),
    path('', include('events.urls')),
    path('masser/', include('mass_mailer.urls')),
    path('certificate/', include('certificate.urls')),
    path('ticket/', include('tickets.urls')),
    path('hospi/', include('hospi.urls')),
    # path("administrator/", include("administrator.urls")),

    path('robowars-bet/', include('robowarsbet.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path("apo/<path:path>", serve),
    path("media/<path:path>", serve),
]

handler404 = custom_404

backend/admins/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin</title>
</head>
<body>
    <div>
        <h1>COMPETITIONS</h1>
        <a href='{% url "admins:compi" "compi"  %}'><h2>All Competitions</h2></a>
        <ul>
            {% for compi in compies %}
            <li>
                <a href='{% url "admins:compi" compiname=compi.name %}'>{{ compi.name }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div>
        <h1>Workshops</h1>
        <a href="{% url 'admins:workshop' 'workshop' %}"><h2>All Workshops</h2></a>
        <ul>
            {% for workshop in workshops %}
            <li>
                <a href="{% url 'admins:workshop' workshopname=workshop.name %}">{{ workshop.name }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <!-- <div>
        <a href="">Accommodation</a>
    </div> -->
</body>
</html>